
services:
  ddos-dev:
    build: .
    container_name: ddos-dev
    ports:
      - "8888:8888"
    volumes:
      - .:/app
    working_dir: /app
    command: ["jupyter", "notebook", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--allow-root", "--NotebookApp.token="]
